---
on:
  push:
    branches:
      - master
      - take-two
  pull_request:
    branches:
      - master
      - take-two
  workflow_dispatch: {}

env:
  CACHE_NAME: golang
  CACHE_VERSION: v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-${{ env.CACHE_NAME }}-${{ env.CACHE_VERSION }}-${{ hashFiles('go.sum') }}"
          restore_keys: |
            ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ env.CACHE_VERSION }}
            ${{ runner.os }}-${{ env.CACHE_NAME }}
            ${{ runner.os }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
      - run: go mod download -x
      - run: go build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-${{ env.CACHE_NAME }}-${{ env.CACHE_VERSION }}-${{ hashFiles('go.sum') }}"
          restore_keys: |
            ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ env.CACHE_VERSION }}
            ${{ runner.os }}-${{ env.CACHE_NAME }}
            ${{ runner.os }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
      - run: go mod download -x
      - run: go test ./...

  audit:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-${{ env.CACHE_NAME }}-${{ env.CACHE_VERSION }}-${{ hashFiles('go.sum') }}"
          restore_keys: |
            ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ env.CACHE_VERSION }}
            ${{ runner.os }}-${{ env.CACHE_NAME }}
            ${{ runner.os }}
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
      - uses: securego/gosec@master
        env:
          GO111MODULE: on
        with:
          args: -color ./...